The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant. One class is linearly separable from the other 2; the latter are NOT linearly separable from each other


Wczytanie danych przy pomocy "pandas"

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
#nazwy kolumn w naszym data_secie
columns = ["Sepal Length", "Sepal Width",
           "Petal Length", "Petal Width",
           "Class"]
#źródło naszych danych
src = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#wczytanie danych za pomocą pandy

iris_data = pd.read_csv(src, header=None, names=columns)
iris_data.head()

Sepal Length  Sepal Width  Petal Length  Petal Width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
X = iris_data.iloc[:, :4]
print(X)

     Sepal Length  Sepal Width  Petal Length  Petal Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [3]:
X = np.array(X)
#zrobiłem z nagłówków liczby, może tak będzie łatwiej
Y_string = np.array(iris_data["Class"])

dictionary = {
  0: "Iris-setosa",
  1: "Iris-versicolor",
  2: "Iris-virginica"
}

Y = []
for i in Y_string:
    if(i=='Iris-setosa'):
        Y.append(0)
    elif(i=='Iris-versicolor'):
        Y.append(1);
    else:
        Y.append(2);

In [4]:
import torch
#tworzenie modelu

input_dimension = 4
output_dimension = 3
hidden_dimension = 16
epochs = 3000

loss_function = torch.nn.MSELoss()

model = torch.nn.Sequential(
torch.nn.Linear(input_dimension, hidden_dimension),
torch.nn.ReLU(),
torch.nn.Linear(hidden_dimension, output_dimension),
torch.nn.Softmax()
)

optimizer = torch.optim.RMSprop(model.parameters())

In [5]:
#utworzenie danych treningowych
x_train = np.concatenate((X[:40], X[50:90], X[100:140]), axis=0)
y_train = np.concatenate((Y[:40], Y[50:90], Y[100:140]), axis=0)
#utworzenie danych testowych
x_test = np.concatenate((X[40:50], X[90:100], X[140:150]), axis=0)
y_test = np.concatenate((Y[40:50], Y[90:100], Y[140:150]), axis=0)
print(y_train)

def to_one_hot(labels, dimension=3):
    results = np.zeros((len(labels),dimension))
    for i, label in enumerate(labels):
        results[i,label] = 1
    return results

print(y_train)
one_hot_train_labels = to_one_hot(y_train)
one_hot_test_labels = to_one_hot(y_test)
print(one_hot_test_labels)
#zamiana na tensory
x_train = torch.tensor(x_train).float()
y_train = torch.tensor(one_hot_train_labels).float()
#zamiana na tensory
x_test = torch.tensor(x_test).float()
y_test = torch.tensor(one_hot_test_labels).float()
                                          

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [6]:
history = []
#history_val = []
#trening modelu
for i in range(epochs):
    y_pred = model(x_train)
    #y_pred_val = model(x_val)
    loss = loss_function(y_pred, y_train)
    #loss_val = loss_function(y_pred_val, y_val)
    
    history.append(loss.detach().numpy().squeeze())
    #history_val.append(loss_val.detach().numpy().squeeze())
    
    optimizer.zero_grad()
    loss.backward()
    
    optimizer.step()

/home/patryk/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py:100: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


In [7]:
y_out=model(x_test)

In [8]:
print(y_out)

tensor([[1.0000e+00, 4.4940e-08, 4.0240e-09],
        [9.9161e-01, 8.3816e-03, 1.0622e-05],
        [1.0000e+00, 1.0113e-06, 3.3010e-08],
        [1.0000e+00, 3.6014e-06, 1.2017e-07],
        [1.0000e+00, 4.9231e-07, 2.6995e-08],
        [9.9998e-01, 1.5340e-05, 1.8250e-07],
        [1.0000e+00, 1.2071e-08, 1.6327e-09],
        [1.0000e+00, 1.6145e-06, 4.1758e-08],
        [1.0000e+00, 1.0328e-08, 1.2700e-09],
        [1.0000e+00, 3.3298e-07, 1.2550e-08],
        [3.0804e-05, 9.9820e-01, 1.7700e-03],
        [2.2157e-05, 9.9875e-01, 1.2309e-03],
        [6.7502e-07, 9.9997e-01, 2.6021e-05],
        [3.4469e-07, 9.9999e-01, 5.4118e-06],
        [9.4955e-06, 9.9951e-01, 4.8116e-04],
        [6.1170e-07, 9.9998e-01, 2.2120e-05],
        [2.7363e-06, 9.9988e-01, 1.1902e-04],
        [8.9511e-07, 9.9996e-01, 3.7789e-05],
        [1.4403e-05, 9.9996e-01, 2.1107e-05],
        [2.0428e-06, 9.9991e-01, 8.8348e-05],
        [2.5463e-03, 1.5454e-03, 9.9591e-01],
        [5.7723e-03, 1.7988e-02, 9

In [10]:
for num, i in enumerate(y_out):
    if(i[0]>=0.5):
        print(f"Iris-setosa")
    elif(i[1]>=0.5):
        print(f"Iris-versicolor")
    elif(i[2]>=0.5):
        print(f"Iris-virginica")

Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-setosa
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-versicolor
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
Iris-virginica
